<table class="table table-success table-striped">
    <tr>
        <td>Title</td>
        <td>Artist</td>
        <td>Release Date</td>
        <td>Rating</td>
        <td>Ver mas</td>
    </tr>
    <?php foreach ($albums as $album) { ?>
        <tr>
            <td> <?= $album->getTitle() ?> </td>
            <td> <?= $album->getArtist() ?></td>
            <td> <?= $album->getRel_date() ?> </td>
            <td><?= $album->getRating() ?></td>
            <a href="album/<?= $album->getId() ?>">
                <td><--></td>
            </a>
        </tr>
    <?php }  ?>
</table>