<table class="table table-success table-striped album_table">
    <tr>
        <td><b>Title</b></td>
        <td><b>Artist</b></td>
        <td><b>Release Date</b></td>
        <td><b>Rating</b></td>
        <td><b>Ver mas</b></td>
    </tr>
    <?php foreach ($albums as $album) { ?>
        <tr id='album_row' data-id="<?=$album->getId()?>">
            <td> <?= $album->getTitle() ?> </td>
            <td> <?= $album->getArtist() ?></td>
            <td> <?= $album->getRel_date() ?> </td>
            <td><?= $album->getRating() ?></td>
            <td><a href="albums/<?= $album->getId() ?>"><button class="button alt">==></button></a></td>
        </tr>
    <?php } ?>
</table>