<div class="card">
    <h2><?php echo $album->getTitle()?></h2>
    <!--Imagenes en la base de datos = WIP-->
    <img src="" alt="" id="cover">
    <div class="rating">
        <?php 
            $count = $album->getRating();
            while ($count > 1) { ?>
                <img src="./img/star.png" alt="star">
            <?php 
                $count = $count-1;
            }
            if (($count > 0) && ($count <= 0.5)){ ?>
                <img src="./img/half_star.png" alt="half_star">
            <?php 
            }
            if ($count > 0.5){
                ?>
                <img src="./img/star.png" alt="star"> 
            <?php }
        ?>
    </div>
    <div class="description">
        <p><?php echo $album->getReview() ?></p>
    </div>
    <a href="/albums/<?php echo $album->getId() ?>"><button class="button card-btn">VER MAS</button></a>
</div>