<div class="card">
    <h2><?=$album->getTitle()?></h2>
    <h6><?=$album->getArtist()?></h6>
    <!--Imagenes en la base de datos = WIP-->
    <img src="<?= $album->getImgUrl() ?>" alt=" <?= "Arte de tapa " . $album->getTitle() ?>" id="cover">
    <div class="rating">
        <?php require './template/rating_stars.phtml'; ?>
    </div>
    <div class="description">
        <p><?=$album->getReview() ?></p>
    </div>
    <a href="albums/<?=$album->getId() ?>"><button class="button card-btn">VER MAS</button></a>
</div>