<section class="album_container">
    <div class="album_data">
        <h2 class='title'><?php echo $album->getTitle();?></h2>
        <img src="" alt="" id="cover">
        <h3 class='artist'><?php echo $album->getArtist();?></h3>
        <div class="rating"><?php require './template/rating_stars.phtml'; ?></div>
        <p class="description"><?php echo $album->getReview()?></p>
    </div>
    <div class="album_songs">
        <?php 
            require_once './template/song_table.phtml';
        ?>
    </div>
</section>