</main>
    <footer>

    </footer>
    <script type="text/javascript" src="js/login_display.js"></script>
<?php if (!empty($action)){ 
    switch ($action) {
        case 'albums':?>
            <script type="text/javascript" src="js/card_display.js"></script>
        <?php break;
        case 'songs':?>
            <script type="text/javascript" src="js/lyric_display.js"></script>
        <?php break;
          case 'admin_panel':?>
            <script type="text/javascript" src="js/modify_panel_display.js"></script>
        <?php break;
    }
    } ?>
</body>

</html>