<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HARMONY HUB - Reseñas de albums</title>
    <link rel="stylesheet" href="./css/style.css">
</head>
<body>
    <header>
        <img src="./img/HARMONY.png" alt="Logo">
        <nav>
            <button class="nav button">INICIO</button>
            <button class="nav button">ULTIMOS LANZAMIENTOS</button>
            <button class="nav button alt">INICIAR SESION</button>
        </nav>
    </header>
    <main>