<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <base href="<?= BASE_URL ?>"> 
    <title>HARMONY HUB - Reseñas de albums</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">
</head>

<body>
    <header>
        <a href="home"><img src="img/HARMONY.png" alt="Logo"></a>
        <nav>
            <a href="home"><button class="nav button">INICIO</button></a>
            <a href="canciones"><button class="nav button">CANCIONES</button></a>
            <a href="404"><button class="nav button">VER ALBUMS</button></a>
            <?php //if (rol del usario = admin){ ?>
            <a href="administracion/albums"><button class="nav button">ADMINISTRACION ALBUMS</button></a>
            <a href="administracion/songs"><button class="nav button">ADMINISTRACION SONGS</button></a>
            <?php //} ?>
            <a href="404"><!--En esta linea hay que hacer un condicional para elegir si redirige a iniciar sesion o a cerrarla-->
                <button class="nav button alt"><?php //if (sesion iniciada){?> 
                    CERRAR
                    <?php //} else echo 'INICIAR'?>
                    SESION
                </button>
            </a>
        </nav>
    </header>
    <main>