<div class="login_container">
    <form class="login_form card" method="POST" action="auth">
        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">User</label>
            <input type="text" name="user" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
        </div>
        <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label">Password</label>
            <input type="password" name="password" class="form-control" id="exampleInputPassword1">
        </div>
        <?php if (isset($error)) { ?>
            <div class='alert alert-danger' role='alert'>
                <?= $error ?>
            </div>
        <?php } ?>
        <div class="login_buttons">
            <button type="submit" class="btn btn-primary button alt">Login</button>
            <?= ($_GET['action'] == 'auth') ? "<a href='home'>" : "" ?>
            <button type="button" class="btn btn-primary button" id="close_form">Cerrar</button>
            <?= ($_GET['action'] == 'auth') ? "</a>" : "" ?>
        </div>
    </form>
</div>