<div class="login_container">
    <form class="login_form card">
    <form class="login_form card">
        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">User</label>
            <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
        </div>
        <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label">Password</label>
            <input type="password" class="form-control" id="exampleInputPassword1">
        </div>
        <div class="login_buttons"> 
        <button type="submit" class="btn btn-primary button alt">Login</button>
        <button type= "button" class="btn btn-primary button" id="close_form">Cerrar</button>
        </div>
    </form>    
</div>