<div class="login_container">
    <div class="login_form card">
        <h3>Estas seguro de que quieres cerrar sesion?</h1>
            <div class="login_buttons">
                <a href="logout"><button type="submit" class="btn btn-primary button alt">SI</button></a>
                <button type="button" class="btn btn-primary button" id="close_form">NO</button>
            </div>
    </div>
</div>