<div class="modify_panel card">
    <h4>Elija la canción a modificar</h4>
    <form action="update/song" method="POST" class="modify-form">
        <?php require_once './template/song_select.phtml';
        $song = null; 
        ?>
        <div class="modify_song_container">  
            <?php
            require_once './template/modify_song_form.phtml';    
            ?>
        </div>
    </form>
 </div>